title: COURSE TITLE # title which appears for the website
email: #your-email@example.com
description: > # short discription of your website. It is helpful for making your website more discoverable and appears while previewing your website.
 
baseurl: "Causal_Inference"   # specify the subpath of your site
url: "https://abnmsry.github.io" # the base hostname & protocol for YOUR site, e.g. http://example.com
twitter_username: #
github_username: abnmsry#
theme: minima
plugins:
  - jekyll-feed
